### ISSUE TITLE
Send the final link to the courses to Laszlo 

### ISSUE THREAD

**Issue by salacika** [CEU-Economics-and-Business/ECBS-5146-Different-Shapes-of-Data#9]
- to update moodle
- to work on further styling

**Comment by korenmiklos** [comment]
Live site: https://ceu-economics-and-business.github.io/ECBS-5146-Different-Shapes-of-Data/
Git repo: https://github.com/CEU-Economics-and-Business/ECBS-5146-Different-Shapes-of-Data

Content is in the `_episodes/` folder.  If you have jekyll at home (a ruby app), type `bundle install` to install all its dependencies and `make serve` to show the site on localhost.
